name: el_csadmin
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.9.2
  get_it: ^9.2.1
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.5
  equatable: ^2.0.8
  trina_grid: ^2.2.2
  fl_chart: ^1.2.0
  encrypt: ^5.0.3
  get_storage: ^2.1.1
  pretty_dio_logger: ^1.4.0
  freezed_annotation: ^3.1.0
  pdf: ^3.13.0
  printing: ^5.14.3
  package_info_plus: ^10.2.1
  window_manager: ^0.5.2
  crypto: ^3.0.7
  path: ^1.9.1
  lottie: ^3.5.1
  mask_text_input_formatter: ^2.9.0
  bloc: ^9.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.1
  freezed: ^4.0.0-dev.3

flutter:
  assets:
    - assets/images/
    - assets/animations/
  uses-material-design: true
